[I 2024-01-31 14:22:33.579 ServerApp] Extension package jupyter_lsp took 0.1699s to import
[W 2024-01-31 14:22:33.579 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
Fail to get yarn configuration. internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /scratch/big/home/davcic/.local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:423:2576
    at Object.<anonymous> (/scratch/big/home/davcic/.local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:743:8770)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

[W 2024-01-31 14:22:34.485 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-31 14:22:34.487 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-01-31 14:22:34.494 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-01-31 14:22:34.498 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-01-31 14:22:34.503 ServerApp] notebook | extension was successfully linked.
[I 2024-01-31 14:22:35.007 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-01-31 14:22:35.054 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-01-31 14:22:35.057 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-01-31 14:22:35.059 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-01-31 14:22:35.063 LabApp] JupyterLab extension loaded from /home/davcic/.local/lib/python3.8/site-packages/jupyterlab
[I 2024-01-31 14:22:35.064 LabApp] JupyterLab application directory is /scratch/big/home/davcic/.local/share/jupyter/lab
[I 2024-01-31 14:22:35.065 LabApp] Extension Manager is 'pypi'.
[I 2024-01-31 14:22:35.068 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-01-31 14:22:35.072 ServerApp] notebook | extension was successfully loaded.
[I 2024-01-31 14:22:35.073 ServerApp] Serving notebooks from local directory: /scratch/big/home/davcic/CP_Testing
[I 2024-01-31 14:22:35.075 ServerApp] Jupyter Server 2.12.1 is running at:
[I 2024-01-31 14:22:35.075 ServerApp] http://localhost:8888/tree?token=39412364a13a80b9a52d78ce8f23f966794442b52e04240a
[I 2024-01-31 14:22:35.075 ServerApp]     http://127.0.0.1:8888/tree?token=39412364a13a80b9a52d78ce8f23f966794442b52e04240a
[I 2024-01-31 14:22:35.075 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-01-31 14:22:35.105 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///scratch/big/home/davcic/.local/share/jupyter/runtime/jpserver-434201-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=39412364a13a80b9a52d78ce8f23f966794442b52e04240a
        http://127.0.0.1:8888/tree?token=39412364a13a80b9a52d78ce8f23f966794442b52e04240a
[I 2024-01-31 14:22:35.373 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-01-31 14:23:01.085 ServerApp] 404 GET /api/contents/CP_Testing/ChangePoint_GP.ipynb?type=notebook&content=1&1706707380633 (26b62d0719794b5e9ed329d52377dee7@127.0.0.1) 77.56ms referer=http://localhost:8888/notebooks/CP_Testing/ChangePoint_GP.ipynb
[W 2024-01-31 14:23:01.086 ServerApp] 404 GET /api/contents/CP_Testing/ChangePoint_GP.ipynb?type=notebook&content=1&1706707380633 (127.0.0.1): No such file or directory: CP_Testing/ChangePoint_GP.ipynb
[W 2024-01-31 14:23:20.087 ServerApp] Notebook ChangePoint_mult_param.ipynb is not trusted
[W 2024-01-31 14:23:23.689 ServerApp] Notebook ChangePoint_mult_param.ipynb is not trusted
[I 2024-01-31 14:23:25.605 ServerApp] Kernel started: a4b2f954-4afa-4fc6-bf4b-9165046e53ef
[I 2024-01-31 14:23:26.551 ServerApp] Connecting to kernel a4b2f954-4afa-4fc6-bf4b-9165046e53ef.
2024-01-31 14:23:41.404791: E external/xla/xla/stream_executor/gpu/asm_compiler.cc:114] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

[I 2024-01-31 14:23:43.590 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-01-31 14:23:43.590 ServerApp] kernel a4b2f954-4afa-4fc6-bf4b-9165046e53ef restarted
[I 2024-01-31 14:23:43.600 ServerApp] Starting buffering for a4b2f954-4afa-4fc6-bf4b-9165046e53ef:a7b64deb-e5a9-4ff7-817f-1309b62e567b
[I 2024-01-31 14:23:43.639 ServerApp] Connecting to kernel a4b2f954-4afa-4fc6-bf4b-9165046e53ef.
[I 2024-01-31 14:23:43.640 ServerApp] Restoring connection for a4b2f954-4afa-4fc6-bf4b-9165046e53ef:a7b64deb-e5a9-4ff7-817f-1309b62e567b
[I 2024-01-31 14:25:24.297 ServerApp] Saving file at /ChangePoint_mult_param.ipynb
[W 2024-01-31 14:25:24.298 ServerApp] Notebook ChangePoint_mult_param.ipynb is not trusted
[I 2024-01-31 18:22:10.631 ServerApp] Starting buffering for a4b2f954-4afa-4fc6-bf4b-9165046e53ef:a7b64deb-e5a9-4ff7-817f-1309b62e567b
[W 2024-03-01 13:20:29.512 ServerApp] 404 GET /hub/api (@127.0.0.1) 354.70ms referer=None
[I 2024-03-01 13:20:29.525 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.17ms
[W 2024-03-01 13:20:29.771 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/davcic/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 762, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-03-01 13:20:29.912 ServerApp] 403 GET /api/kernelspecs?1709295629759 (@127.0.0.1) 142.68ms referer=None
[W 2024-03-01 13:20:29.913 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/davcic/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 762, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-03-01 13:20:29.915 ServerApp] 403 GET /api/kernels?1709295629762 (@127.0.0.1) 145.27ms referer=None
[W 2024-03-01 13:20:29.917 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/davcic/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 762, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-03-01 13:20:29.918 ServerApp] 403 GET /api/kernels?1709295629764 (@127.0.0.1) 2.42ms referer=None
[W 2024-03-01 13:20:29.919 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/davcic/.local/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/davcic/.local/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 762, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-03-01 13:20:29.920 ServerApp] 403 GET /api/sessions?1709295629765 (@127.0.0.1) 3.46ms referer=None
